/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.savaco.gui;

import com.savaco.ConfigurationAgent.AssetThing;
import com.savaco.ConfigurationAgent.ConfigurationAgent;
import com.savaco.testapplication.ProductLineClient;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import javafx.concurrent.Task;
import javax.swing.border.Border;

/**
 *
 * @author Administrator
 */
public class VirtualProductLineGUI extends javax.swing.JFrame {

    ConfigurationAgent agent;
    ProductLineClient client;

    /**
     * Creates new form VirtualProductLineGUI
     *
     * @param agent
     */
    public VirtualProductLineGUI(ConfigurationAgent agent) {
        initComponents();
        setLocationRelativeTo(null);
        this.agent = agent;
        this.client = agent.getClient();
    }

    private void initializeComponentsFromConfigurationFile() {
        try {
            client.start();
            Task t = new Task() {
                @Override
                protected Object call() throws Exception {
                    client.startInitialization();
                    TimeUnit.MINUTES.sleep(10);
                    client.shutdown();
                    return null;
                }
            };
        } catch (Exception e) {
            System.out.println("An exception occurred during initializing the components");
        }

    }

    private void updateStatus() {
        this.PBStatusLabelValue.setText(this.agent.getAssetsAsThings().get(1).convertToState(Integer.parseInt(this.agent.getAssetsAsThings().get(1).getPropertyByName("status").getValue())).toString());
        this.PCStatusLabelValue.setText(this.agent.getAssetsAsThings().get(2).convertToState(Integer.parseInt(this.agent.getAssetsAsThings().get(1).getPropertyByName("status").getValue())).toString());
        this.AStatusLabelValue.setText(this.agent.getAssetsAsThings().get(3).convertToState(Integer.parseInt(this.agent.getAssetsAsThings().get(1).getPropertyByName("status").getValue())).toString());
        this.QCStatusLabelValue.setText(this.agent.getAssetsAsThings().get(4).convertToState(Integer.parseInt(this.agent.getAssetsAsThings().get(1).getPropertyByName("status").getValue())).toString());
        this.LStatusLabelValue.setText(this.agent.getAssetsAsThings().get(5).convertToState(Integer.parseInt(this.agent.getAssetsAsThings().get(1).getPropertyByName("status").getValue())).toString());
        this.BStatusLabelValue.setText(this.agent.getAssetsAsThings().get(6).convertToState(Integer.parseInt(this.agent.getAssetsAsThings().get(1).getPropertyByName("status").getValue())).toString());
        this.PStatusLabelValue.setText(this.agent.getAssetsAsThings().get(7).convertToState(Integer.parseInt(this.agent.getAssetsAsThings().get(1).getPropertyByName("status").getValue())).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProducerBPanel3 = new javax.swing.JPanel();
        PBStatusLabel3 = new javax.swing.JLabel();
        PBLabelStatusValue3 = new javax.swing.JLabel();
        PBPRLabel3 = new javax.swing.JLabel();
        PBPRValue3 = new javax.swing.JSpinner();
        PBDetailsButton3 = new javax.swing.JButton();
        PBBreakButton3 = new javax.swing.JButton();
        PBMaintenanceButton3 = new javax.swing.JButton();
        ProducerC = new javax.swing.JPanel();
        PCStatusLabel = new javax.swing.JLabel();
        PBLabelStatusValue1 = new javax.swing.JLabel();
        PCPRLabel = new javax.swing.JLabel();
        PCPRValue = new javax.swing.JSpinner();
        PCDetailsButton = new javax.swing.JButton();
        PCBreakButton = new javax.swing.JButton();
        PCMaintenanceButton = new javax.swing.JButton();
        PCStatusLabelValue = new javax.swing.JLabel();
        QualityChecker = new javax.swing.JPanel();
        QCStatusLabel = new javax.swing.JLabel();
        PBLabelStatusValue2 = new javax.swing.JLabel();
        QCPRLabel = new javax.swing.JLabel();
        QCPRValue = new javax.swing.JSpinner();
        QCDetailsButton = new javax.swing.JButton();
        QCBreakButton = new javax.swing.JButton();
        QCMaintenanceButton = new javax.swing.JButton();
        QCStatusLabelValue = new javax.swing.JLabel();
        Assembler = new javax.swing.JPanel();
        AStatusLabel = new javax.swing.JLabel();
        PBLabelStatusValue4 = new javax.swing.JLabel();
        APRLabel = new javax.swing.JLabel();
        APRValue = new javax.swing.JSpinner();
        ADetailsButton = new javax.swing.JButton();
        ABreakButton = new javax.swing.JButton();
        AMaintenanceButton = new javax.swing.JButton();
        AStatusLabelValue = new javax.swing.JLabel();
        Labeler = new javax.swing.JPanel();
        LStatusLabel = new javax.swing.JLabel();
        LPRLabel = new javax.swing.JLabel();
        LPRValue = new javax.swing.JSpinner();
        LDetailsButton = new javax.swing.JButton();
        LBreakButton = new javax.swing.JButton();
        LMaintenanceButton = new javax.swing.JButton();
        LStatusLabelValue = new javax.swing.JLabel();
        Palletizer = new javax.swing.JPanel();
        PStatusLabel = new javax.swing.JLabel();
        PPRLabel = new javax.swing.JLabel();
        PPRValue = new javax.swing.JSpinner();
        PDetailsButton = new javax.swing.JButton();
        PBreakButton = new javax.swing.JButton();
        PMaintenanceButton = new javax.swing.JButton();
        PStatusLabelValue = new javax.swing.JLabel();
        Boxer = new javax.swing.JPanel();
        BStatusLabel = new javax.swing.JLabel();
        BPRLabel = new javax.swing.JLabel();
        BPRValue = new javax.swing.JSpinner();
        BDetailsButton = new javax.swing.JButton();
        BBreakButton = new javax.swing.JButton();
        BMaintenanceButton = new javax.swing.JButton();
        BStatusLabelValue = new javax.swing.JLabel();
        ProducerB = new javax.swing.JPanel();
        PBStatusLabel1 = new javax.swing.JLabel();
        PBLabelStatusValue8 = new javax.swing.JLabel();
        PBPRLabel = new javax.swing.JLabel();
        PBPRValue = new javax.swing.JSpinner();
        PBDetailsButton = new javax.swing.JButton();
        PBBreakButton = new javax.swing.JButton();
        PBMaintenanceButton = new javax.swing.JButton();
        PBStatusLabelValue = new javax.swing.JLabel();
        Optionespanel = new javax.swing.JPanel();
        RandomDataButton = new javax.swing.JToggleButton();

        ProducerBPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assembler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        PBStatusLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PBStatusLabel3.setText("Status: ");

        PBPRLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PBPRLabel3.setText("Production Rate: ");

        PBDetailsButton3.setLabel("Details...");
        PBDetailsButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBDetailsButton3ActionPerformed(evt);
            }
        });

        PBBreakButton3.setLabel("Break");

        PBMaintenanceButton3.setLabel("Maintenance");

        javax.swing.GroupLayout ProducerBPanel3Layout = new javax.swing.GroupLayout(ProducerBPanel3);
        ProducerBPanel3.setLayout(ProducerBPanel3Layout);
        ProducerBPanel3Layout.setHorizontalGroup(
            ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(PBDetailsButton3)
                        .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PBStatusLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                                .addComponent(PBPRLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PBPRValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                        .addComponent(PBBreakButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PBMaintenanceButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProducerBPanel3Layout.setVerticalGroup(
            ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PBLabelStatusValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PBStatusLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PBPRLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PBPRValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(PBDetailsButton3)
                .addGap(18, 18, 18)
                .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PBBreakButton3)
                    .addComponent(PBMaintenanceButton3))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VirtualProductLine");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 650));

        ProducerC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producer C", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        PCStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PCStatusLabel.setText("Status: ");

        PCPRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PCPRLabel.setText("Production Rate: ");

        PCDetailsButton.setLabel("Details...");
        PCDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCDetailsButtonActionPerformed(evt);
            }
        });

        PCBreakButton.setLabel("Break");

        PCMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout ProducerCLayout = new javax.swing.GroupLayout(ProducerC);
        ProducerC.setLayout(ProducerCLayout);
        ProducerCLayout.setHorizontalGroup(
            ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProducerCLayout.createSequentialGroup()
                        .addComponent(PCBreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PCMaintenanceButton))
                    .addGroup(ProducerCLayout.createSequentialGroup()
                        .addComponent(PCPRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PCPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProducerCLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PCDetailsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProducerCLayout.createSequentialGroup()
                                .addComponent(PCStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PCStatusLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProducerCLayout.setVerticalGroup(
            ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProducerCLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProducerCLayout.createSequentialGroup()
                        .addGroup(ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PCStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PCStatusLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PCPRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PCPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(PCDetailsButton)
                        .addGap(18, 18, 18)
                        .addGroup(ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PCBreakButton)
                            .addComponent(PCMaintenanceButton))
                        .addContainerGap())
                    .addGroup(ProducerCLayout.createSequentialGroup()
                        .addComponent(PBLabelStatusValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );

        QualityChecker.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quality Checker", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        QCStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        QCStatusLabel.setText("Status: ");

        QCPRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        QCPRLabel.setText("Production Rate: ");

        QCDetailsButton.setLabel("Details...");
        QCDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QCDetailsButtonActionPerformed(evt);
            }
        });

        QCBreakButton.setLabel("Break");

        QCMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout QualityCheckerLayout = new javax.swing.GroupLayout(QualityChecker);
        QualityChecker.setLayout(QualityCheckerLayout);
        QualityCheckerLayout.setHorizontalGroup(
            QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QualityCheckerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(QualityCheckerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QCMaintenanceButton)
                            .addComponent(QCDetailsButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, QualityCheckerLayout.createSequentialGroup()
                        .addGroup(QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QCBreakButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, QualityCheckerLayout.createSequentialGroup()
                                    .addComponent(QCPRLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(QCPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, QualityCheckerLayout.createSequentialGroup()
                                    .addComponent(QCStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(QCStatusLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        QualityCheckerLayout.setVerticalGroup(
            QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QualityCheckerLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QualityCheckerLayout.createSequentialGroup()
                        .addGroup(QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QCStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QualityCheckerLayout.createSequentialGroup()
                                .addComponent(QCStatusLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QCPRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QCPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(QCDetailsButton)
                        .addGap(18, 18, 18)
                        .addGroup(QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QCBreakButton)
                            .addComponent(QCMaintenanceButton))
                        .addContainerGap())
                    .addGroup(QualityCheckerLayout.createSequentialGroup()
                        .addComponent(PBLabelStatusValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );

        Assembler.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assembler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        AStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AStatusLabel.setText("Status: ");

        APRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        APRLabel.setText("Production Rate: ");

        ADetailsButton.setLabel("Details...");
        ADetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADetailsButtonActionPerformed(evt);
            }
        });

        ABreakButton.setLabel("Break");

        AMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout AssemblerLayout = new javax.swing.GroupLayout(Assembler);
        Assembler.setLayout(AssemblerLayout);
        AssemblerLayout.setHorizontalGroup(
            AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssemblerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ADetailsButton)
                    .addGroup(AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(AssemblerLayout.createSequentialGroup()
                            .addComponent(AStatusLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(AStatusLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AssemblerLayout.createSequentialGroup()
                            .addComponent(APRLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(APRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AssemblerLayout.createSequentialGroup()
                            .addComponent(ABreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                            .addComponent(AMaintenanceButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AssemblerLayout.setVerticalGroup(
            AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssemblerLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(PBLabelStatusValue4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(AssemblerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AStatusLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(APRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(APRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(ADetailsButton)
                .addGap(18, 18, 18)
                .addGroup(AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ABreakButton)
                    .addComponent(AMaintenanceButton))
                .addContainerGap())
        );

        Labeler.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Labeler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        LStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LStatusLabel.setText("Status: ");

        LPRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LPRLabel.setText("Production Rate: ");

        LDetailsButton.setLabel("Details...");
        LDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDetailsButtonActionPerformed(evt);
            }
        });

        LBreakButton.setLabel("Break");

        LMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout LabelerLayout = new javax.swing.GroupLayout(Labeler);
        Labeler.setLayout(LabelerLayout);
        LabelerLayout.setHorizontalGroup(
            LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LabelerLayout.createSequentialGroup()
                        .addComponent(LBreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LMaintenanceButton))
                    .addGroup(LabelerLayout.createSequentialGroup()
                        .addComponent(LStatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LStatusLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LabelerLayout.createSequentialGroup()
                        .addComponent(LPRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LabelerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LDetailsButton)))
                .addContainerGap())
        );
        LabelerLayout.setVerticalGroup(
            LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LStatusLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(LDetailsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBreakButton)
                    .addComponent(LMaintenanceButton))
                .addContainerGap())
        );

        Palletizer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Palletizer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        PStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PStatusLabel.setText("Status: ");

        PPRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PPRLabel.setText("Production Rate: ");

        PDetailsButton.setLabel("Details...");
        PDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDetailsButtonActionPerformed(evt);
            }
        });

        PBreakButton.setLabel("Break");

        PMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout PalletizerLayout = new javax.swing.GroupLayout(Palletizer);
        Palletizer.setLayout(PalletizerLayout);
        PalletizerLayout.setHorizontalGroup(
            PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PalletizerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PalletizerLayout.createSequentialGroup()
                        .addComponent(PPRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PalletizerLayout.createSequentialGroup()
                        .addComponent(PBreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PMaintenanceButton))
                    .addGroup(PalletizerLayout.createSequentialGroup()
                        .addComponent(PStatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PStatusLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PalletizerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PDetailsButton)))
                .addContainerGap())
        );
        PalletizerLayout.setVerticalGroup(
            PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PalletizerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PStatusLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PPRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PDetailsButton)
                .addGap(18, 18, 18)
                .addGroup(PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PBreakButton)
                    .addComponent(PMaintenanceButton))
                .addGap(36, 36, 36))
        );

        Boxer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Boxer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        BStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BStatusLabel.setText("Status: ");

        BPRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BPRLabel.setText("Production Rate: ");

        BDetailsButton.setLabel("Details...");
        BDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDetailsButtonActionPerformed(evt);
            }
        });

        BBreakButton.setLabel("Break");

        BMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout BoxerLayout = new javax.swing.GroupLayout(Boxer);
        Boxer.setLayout(BoxerLayout);
        BoxerLayout.setHorizontalGroup(
            BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BoxerLayout.createSequentialGroup()
                        .addComponent(BBreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BMaintenanceButton))
                    .addGroup(BoxerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BoxerLayout.createSequentialGroup()
                                .addComponent(BStatusLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BStatusLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxerLayout.createSequentialGroup()
                                .addComponent(BPRLabel)
                                .addGap(45, 45, 45)
                                .addGroup(BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BDetailsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BPRValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(143, 143, 143))
        );
        BoxerLayout.setVerticalGroup(
            BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BStatusLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BPRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BDetailsButton)
                .addGap(27, 27, 27)
                .addGroup(BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBreakButton)
                    .addComponent(BMaintenanceButton))
                .addContainerGap())
        );

        ProducerB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producer B", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N
        ProducerB.setPreferredSize(new java.awt.Dimension(0, 0));

        PBStatusLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PBStatusLabel1.setText("Status: ");

        PBPRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PBPRLabel.setText("Production Rate: ");

        PBDetailsButton.setLabel("Details...");
        PBDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBDetailsButtonActionPerformed(evt);
            }
        });

        PBBreakButton.setLabel("Break");
        PBBreakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBBreakButtonActionPerformed(evt);
            }
        });

        PBMaintenanceButton.setLabel("Maintenance");

        PBStatusLabelValue.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout ProducerBLayout = new javax.swing.GroupLayout(ProducerB);
        ProducerB.setLayout(ProducerBLayout);
        ProducerBLayout.setHorizontalGroup(
            ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProducerBLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PBDetailsButton))
                    .addGroup(ProducerBLayout.createSequentialGroup()
                        .addGroup(ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ProducerBLayout.createSequentialGroup()
                                .addComponent(PBStatusLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PBStatusLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProducerBLayout.createSequentialGroup()
                                .addComponent(PBBreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(PBMaintenanceButton))
                            .addGroup(ProducerBLayout.createSequentialGroup()
                                .addComponent(PBPRLabel)
                                .addGap(49, 49, 49)
                                .addComponent(PBPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProducerBLayout.setVerticalGroup(
            ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(PBLabelStatusValue8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(ProducerBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PBStatusLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PBStatusLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PBPRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PBPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(PBDetailsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PBBreakButton)
                    .addComponent(PBMaintenanceButton))
                .addContainerGap())
        );

        Optionespanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 2, 14))); // NOI18N

        RandomDataButton.setText("Simulate random data");
        RandomDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OptionespanelLayout = new javax.swing.GroupLayout(Optionespanel);
        Optionespanel.setLayout(OptionespanelLayout);
        OptionespanelLayout.setHorizontalGroup(
            OptionespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionespanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RandomDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        OptionespanelLayout.setVerticalGroup(
            OptionespanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionespanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RandomDataButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Labeler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProducerB, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Palletizer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Optionespanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(594, 594, 594))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Boxer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ProducerC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Assembler, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QualityChecker, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Boxer, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Assembler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(QualityChecker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ProducerB, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProducerC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(Labeler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Optionespanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Palletizer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PCDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCDetailsButtonActionPerformed

    private void QCDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QCDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QCDetailsButtonActionPerformed

    private void PBDetailsButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBDetailsButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PBDetailsButton3ActionPerformed

    private void ADetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADetailsButtonActionPerformed

    private void LDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LDetailsButtonActionPerformed

    private void PDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDetailsButtonActionPerformed

    private void PBDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PBDetailsButtonActionPerformed

    private void PBBreakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBBreakButtonActionPerformed

        AssetThing at = this.agent.getAssetsAsThings().get(1);
        if (this.PBBreakButton.getText().equalsIgnoreCase("Break")) {
            this.PBBreakButton.setText("Restart");
            at.breakThing();
        } else {
            this.PBBreakButton.setText("Break");
            at.restartThing(500);
        }
        this.updateStatus();

    }//GEN-LAST:event_PBBreakButtonActionPerformed

    private void RandomDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomDataButtonActionPerformed
        Task task = new Task() {
            @Override
            protected Object call() throws Exception {
                client.startSimulation();
                return null;
            }
        };
        task.run();
    }//GEN-LAST:event_RandomDataButtonActionPerformed

    private void BDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BDetailsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirtualProductLineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VirtualProductLineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirtualProductLineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirtualProductLineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VirtualProductLineGUI(new ConfigurationAgent("configuration.xml")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABreakButton;
    private javax.swing.JButton ADetailsButton;
    private javax.swing.JButton AMaintenanceButton;
    private javax.swing.JLabel APRLabel;
    private javax.swing.JSpinner APRValue;
    private javax.swing.JLabel AStatusLabel;
    private javax.swing.JLabel AStatusLabelValue;
    private javax.swing.JPanel Assembler;
    private javax.swing.JButton BBreakButton;
    private javax.swing.JButton BDetailsButton;
    private javax.swing.JButton BMaintenanceButton;
    private javax.swing.JLabel BPRLabel;
    private javax.swing.JSpinner BPRValue;
    private javax.swing.JLabel BStatusLabel;
    private javax.swing.JLabel BStatusLabelValue;
    private javax.swing.JPanel Boxer;
    private javax.swing.JButton LBreakButton;
    private javax.swing.JButton LDetailsButton;
    private javax.swing.JButton LMaintenanceButton;
    private javax.swing.JLabel LPRLabel;
    private javax.swing.JSpinner LPRValue;
    private javax.swing.JLabel LStatusLabel;
    private javax.swing.JLabel LStatusLabelValue;
    private javax.swing.JPanel Labeler;
    private javax.swing.JPanel Optionespanel;
    private javax.swing.JButton PBBreakButton;
    private javax.swing.JButton PBBreakButton3;
    private javax.swing.JButton PBDetailsButton;
    private javax.swing.JButton PBDetailsButton3;
    private javax.swing.JLabel PBLabelStatusValue1;
    private javax.swing.JLabel PBLabelStatusValue2;
    private javax.swing.JLabel PBLabelStatusValue3;
    private javax.swing.JLabel PBLabelStatusValue4;
    private javax.swing.JLabel PBLabelStatusValue8;
    private javax.swing.JButton PBMaintenanceButton;
    private javax.swing.JButton PBMaintenanceButton3;
    private javax.swing.JLabel PBPRLabel;
    private javax.swing.JLabel PBPRLabel3;
    private javax.swing.JSpinner PBPRValue;
    private javax.swing.JSpinner PBPRValue3;
    private javax.swing.JLabel PBStatusLabel1;
    private javax.swing.JLabel PBStatusLabel3;
    private javax.swing.JLabel PBStatusLabelValue;
    private javax.swing.JButton PBreakButton;
    private javax.swing.JButton PCBreakButton;
    private javax.swing.JButton PCDetailsButton;
    private javax.swing.JButton PCMaintenanceButton;
    private javax.swing.JLabel PCPRLabel;
    private javax.swing.JSpinner PCPRValue;
    private javax.swing.JLabel PCStatusLabel;
    private javax.swing.JLabel PCStatusLabelValue;
    private javax.swing.JButton PDetailsButton;
    private javax.swing.JButton PMaintenanceButton;
    private javax.swing.JLabel PPRLabel;
    private javax.swing.JSpinner PPRValue;
    private javax.swing.JLabel PStatusLabel;
    private javax.swing.JLabel PStatusLabelValue;
    private javax.swing.JPanel Palletizer;
    private javax.swing.JPanel ProducerB;
    private javax.swing.JPanel ProducerBPanel3;
    private javax.swing.JPanel ProducerC;
    private javax.swing.JButton QCBreakButton;
    private javax.swing.JButton QCDetailsButton;
    private javax.swing.JButton QCMaintenanceButton;
    private javax.swing.JLabel QCPRLabel;
    private javax.swing.JSpinner QCPRValue;
    private javax.swing.JLabel QCStatusLabel;
    private javax.swing.JLabel QCStatusLabelValue;
    private javax.swing.JPanel QualityChecker;
    private javax.swing.JToggleButton RandomDataButton;
    // End of variables declaration//GEN-END:variables
}
