/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.savaco.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Administrator
 */
public class VirtualProductLineUI extends javax.swing.JFrame {

    /**
     * Creates new form VirtualProductLineUI
     */
    UIAgent agent;
    
    public VirtualProductLineUI(UIAgent agent) {
        initComponents();
        this.agent = agent;
        new Timer(1000, taskPerformer).start();
    }
    
    ActionListener taskPerformer = new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent evt){
            updateStatus();
            //updateProdRates();
        }
    };
    
    public void updateStatus(){
        agent.getAllStatus();
        /*this.PBStatus.setText(agent.getStatus().get(1));
        this.PCStatus.setText(agent.getStatus().get(2));
        this.AStatus.setText(agent.getStatus().get(3));
        this.QCStatus.setText(agent.getStatus().get(4));
        this.LStatus.setText(agent.getStatus().get(5));
        this.BStatus.setText(agent.getStatus().get(6));
        this.PStatus.setText(agent.getStatus().get(7));*/
    }
    
    public void updateProdRates(){
        agent.getAllProdRates();
        this.PBStatus.setText(agent.getProdRates().get(1).toString());
        this.PCStatus.setText(agent.getProdRates().get(2).toString());
        this.AStatus.setText(agent.getProdRates().get(3).toString());
        this.QCStatus.setText(agent.getProdRates().get(4).toString());
        this.LStatus.setText(agent.getProdRates().get(5).toString());
        this.BStatus.setText(agent.getProdRates().get(6).toString());
        this.PStatus.setText(agent.getProdRates().get(7).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProducerBPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PBStatus = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PBProdRate = new javax.swing.JSpinner();
        PBDetails = new javax.swing.JButton();
        ProducerBPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PCStatus = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PCProdRate = new javax.swing.JSpinner();
        PCDetails = new javax.swing.JButton();
        ProducerBPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AStatus = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        AProdRate = new javax.swing.JSpinner();
        ADetails = new javax.swing.JButton();
        ProducerBPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        QCStatus = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        QCProdRate = new javax.swing.JSpinner();
        QCDetails = new javax.swing.JButton();
        ProducerBPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LStatus = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LProdRate = new javax.swing.JSpinner();
        LDetails = new javax.swing.JButton();
        ProducerBPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BStatus = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BProdRate = new javax.swing.JSpinner();
        BDetails = new javax.swing.JButton();
        ProducerBPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PStatus = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PProdRate = new javax.swing.JSpinner();
        PDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("VirtualProductLie"); // NOI18N

        ProducerBPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Producer B"));
        ProducerBPanel.setPreferredSize(new java.awt.Dimension(225, 200));

        jLabel1.setText("Status:");
        jLabel1.setMinimumSize(new java.awt.Dimension(45, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(35, 20));

        PBStatus.setMinimumSize(new java.awt.Dimension(15, 15));

        jLabel8.setText("Production Rate:");

        PBDetails.setText("Details...");

        javax.swing.GroupLayout ProducerBPanelLayout = new javax.swing.GroupLayout(ProducerBPanel);
        ProducerBPanel.setLayout(ProducerBPanelLayout);
        ProducerBPanelLayout.setHorizontalGroup(
            ProducerBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProducerBPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PBStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProducerBPanelLayout.createSequentialGroup()
                        .addGroup(ProducerBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PBDetails)
                            .addGroup(ProducerBPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PBProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ProducerBPanelLayout.setVerticalGroup(
            ProducerBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PBStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ProducerBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PBProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PBDetails)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        ProducerBPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Producer C"));
        ProducerBPanel1.setPreferredSize(new java.awt.Dimension(225, 200));

        jLabel3.setText("Status:");
        jLabel3.setPreferredSize(new java.awt.Dimension(35, 20));

        PCStatus.setMinimumSize(new java.awt.Dimension(15, 15));

        jLabel9.setText("Production Rate:");

        PCDetails.setText("Details...");

        javax.swing.GroupLayout ProducerBPanel1Layout = new javax.swing.GroupLayout(ProducerBPanel1);
        ProducerBPanel1.setLayout(ProducerBPanel1Layout);
        ProducerBPanel1Layout.setHorizontalGroup(
            ProducerBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProducerBPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PCStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProducerBPanel1Layout.createSequentialGroup()
                        .addGroup(ProducerBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PCDetails)
                            .addGroup(ProducerBPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PCProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ProducerBPanel1Layout.setVerticalGroup(
            ProducerBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PCStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ProducerBPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PCProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PCDetails)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        ProducerBPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Assembler"));
        ProducerBPanel2.setPreferredSize(new java.awt.Dimension(225, 200));

        jLabel2.setText("Status:");
        jLabel2.setPreferredSize(new java.awt.Dimension(35, 20));

        AStatus.setMinimumSize(new java.awt.Dimension(15, 15));

        jLabel10.setText("Production Rate:");

        ADetails.setText("Details...");

        javax.swing.GroupLayout ProducerBPanel2Layout = new javax.swing.GroupLayout(ProducerBPanel2);
        ProducerBPanel2.setLayout(ProducerBPanel2Layout);
        ProducerBPanel2Layout.setHorizontalGroup(
            ProducerBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProducerBPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(ProducerBPanel2Layout.createSequentialGroup()
                        .addGroup(ProducerBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ADetails)
                            .addGroup(ProducerBPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        ProducerBPanel2Layout.setVerticalGroup(
            ProducerBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ProducerBPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ADetails)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        ProducerBPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Quality Checker"));
        ProducerBPanel3.setPreferredSize(new java.awt.Dimension(225, 200));

        jLabel4.setText("Status:");
        jLabel4.setPreferredSize(new java.awt.Dimension(35, 20));

        QCStatus.setMinimumSize(new java.awt.Dimension(15, 15));

        jLabel11.setText("Production Rate:");

        QCDetails.setText("Details...");

        javax.swing.GroupLayout ProducerBPanel3Layout = new javax.swing.GroupLayout(ProducerBPanel3);
        ProducerBPanel3.setLayout(ProducerBPanel3Layout);
        ProducerBPanel3Layout.setHorizontalGroup(
            ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QCStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                        .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QCDetails)
                            .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(QCProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ProducerBPanel3Layout.setVerticalGroup(
            ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QCProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(QCDetails)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        ProducerBPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Labeler"));
        ProducerBPanel4.setPreferredSize(new java.awt.Dimension(225, 200));

        jLabel5.setText("Status:");
        jLabel5.setPreferredSize(new java.awt.Dimension(35, 20));

        LStatus.setMinimumSize(new java.awt.Dimension(15, 15));

        jLabel12.setText("Production Rate:");

        LDetails.setText("Details...");

        javax.swing.GroupLayout ProducerBPanel4Layout = new javax.swing.GroupLayout(ProducerBPanel4);
        ProducerBPanel4.setLayout(ProducerBPanel4Layout);
        ProducerBPanel4Layout.setHorizontalGroup(
            ProducerBPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProducerBPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProducerBPanel4Layout.createSequentialGroup()
                        .addGroup(ProducerBPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LDetails)
                            .addGroup(ProducerBPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ProducerBPanel4Layout.setVerticalGroup(
            ProducerBPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProducerBPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LDetails)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        ProducerBPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Boxing Machine"));
        ProducerBPanel5.setPreferredSize(new java.awt.Dimension(225, 200));

        jLabel6.setText("Status:");
        jLabel6.setPreferredSize(new java.awt.Dimension(35, 20));

        BStatus.setMinimumSize(new java.awt.Dimension(15, 15));

        jLabel13.setText("Production Rate:");

        BDetails.setText("Details...");

        javax.swing.GroupLayout ProducerBPanel5Layout = new javax.swing.GroupLayout(ProducerBPanel5);
        ProducerBPanel5.setLayout(ProducerBPanel5Layout);
        ProducerBPanel5Layout.setHorizontalGroup(
            ProducerBPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProducerBPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProducerBPanel5Layout.createSequentialGroup()
                        .addGroup(ProducerBPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BDetails)
                            .addGroup(ProducerBPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ProducerBPanel5Layout.setVerticalGroup(
            ProducerBPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProducerBPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BDetails)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        ProducerBPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Palletizer"));
        ProducerBPanel6.setPreferredSize(new java.awt.Dimension(225, 200));

        jLabel7.setText("Status:");
        jLabel7.setPreferredSize(new java.awt.Dimension(35, 20));

        PStatus.setMinimumSize(new java.awt.Dimension(15, 15));

        jLabel14.setText("Production Rate:");

        PDetails.setText("Details...");

        javax.swing.GroupLayout ProducerBPanel6Layout = new javax.swing.GroupLayout(ProducerBPanel6);
        ProducerBPanel6.setLayout(ProducerBPanel6Layout);
        ProducerBPanel6Layout.setHorizontalGroup(
            ProducerBPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProducerBPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProducerBPanel6Layout.createSequentialGroup()
                        .addGroup(ProducerBPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PDetails)
                            .addGroup(ProducerBPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ProducerBPanel6Layout.setVerticalGroup(
            ProducerBPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ProducerBPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PProdRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PDetails)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ProducerBPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ProducerBPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                        .addComponent(ProducerBPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProducerBPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(ProducerBPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProducerBPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(ProducerBPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProducerBPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProducerBPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProducerBPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProducerBPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProducerBPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProducerBPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(ProducerBPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VirtualProductLineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VirtualProductLineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VirtualProductLineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VirtualProductLineUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VirtualProductLineUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADetails;
    private javax.swing.JSpinner AProdRate;
    private javax.swing.JLabel AStatus;
    private javax.swing.JButton BDetails;
    private javax.swing.JSpinner BProdRate;
    private javax.swing.JLabel BStatus;
    private javax.swing.JButton LDetails;
    private javax.swing.JSpinner LProdRate;
    private javax.swing.JLabel LStatus;
    private javax.swing.JButton PBDetails;
    private javax.swing.JSpinner PBProdRate;
    private javax.swing.JLabel PBStatus;
    private javax.swing.JButton PCDetails;
    private javax.swing.JSpinner PCProdRate;
    private javax.swing.JLabel PCStatus;
    private javax.swing.JButton PDetails;
    private javax.swing.JSpinner PProdRate;
    private javax.swing.JLabel PStatus;
    private javax.swing.JPanel ProducerBPanel;
    private javax.swing.JPanel ProducerBPanel1;
    private javax.swing.JPanel ProducerBPanel2;
    private javax.swing.JPanel ProducerBPanel3;
    private javax.swing.JPanel ProducerBPanel4;
    private javax.swing.JPanel ProducerBPanel5;
    private javax.swing.JPanel ProducerBPanel6;
    private javax.swing.JButton QCDetails;
    private javax.swing.JSpinner QCProdRate;
    private javax.swing.JLabel QCStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
