/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.savaco.gui;

import com.savaco.ConfigurationAgent.AssetThing;
import com.savaco.ConfigurationAgent.ConfigurationAgent;
import com.savaco.testapplication.ProductLineClient;
import javafx.concurrent.Task;
import javax.swing.border.Border;

/**
 *
 * @author Administrator
 */
public class VirtualProductLineGUI extends javax.swing.JFrame {
    
    ConfigurationAgent agent;
    
    /**
     * Creates new form VirtualProductLineGUI
     * @param agent
     */
    public VirtualProductLineGUI(ConfigurationAgent agent) {
        initComponents();
        setLocationRelativeTo(null);
        this.agent = agent;
        this.initializeComponentsFromConfigurationFile();
    }
    
    private void initializeComponentsFromConfigurationFile(){
        ProductLineClient client = this.agent.getClient();
        Task task = new Task() {
            @Override
            protected Object call() throws Exception {
               client.startApplication();
               return null;
            }
        };
        task.run();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProducerBPanel3 = new javax.swing.JPanel();
        PBStatusLabel3 = new javax.swing.JLabel();
        PBLabelStatusValue3 = new javax.swing.JLabel();
        PBPRLabel3 = new javax.swing.JLabel();
        PBPRValue3 = new javax.swing.JSpinner();
        PBDetailsButton3 = new javax.swing.JButton();
        PBBreakButton3 = new javax.swing.JButton();
        PBMaintenanceButton3 = new javax.swing.JButton();
        ProducerC = new javax.swing.JPanel();
        PCStatusLabel = new javax.swing.JLabel();
        PBLabelStatusValue1 = new javax.swing.JLabel();
        PCPRLabel = new javax.swing.JLabel();
        PCPRValue = new javax.swing.JSpinner();
        PCDetailsButton = new javax.swing.JButton();
        PCBreakButton = new javax.swing.JButton();
        PCMaintenanceButton = new javax.swing.JButton();
        PCStatusLabelValue1 = new javax.swing.JLabel();
        QualityChecker = new javax.swing.JPanel();
        QCStatusLabel = new javax.swing.JLabel();
        PBLabelStatusValue2 = new javax.swing.JLabel();
        QCPRLabel = new javax.swing.JLabel();
        QCPRValue = new javax.swing.JSpinner();
        QCDetailsButton = new javax.swing.JButton();
        QCBreakButton = new javax.swing.JButton();
        QCMaintenanceButton = new javax.swing.JButton();
        QCStatusLabelValue1 = new javax.swing.JLabel();
        Assembler = new javax.swing.JPanel();
        AStatusLabel = new javax.swing.JLabel();
        PBLabelStatusValue4 = new javax.swing.JLabel();
        APRLabel = new javax.swing.JLabel();
        APRValue = new javax.swing.JSpinner();
        ADetailsButton = new javax.swing.JButton();
        ABreakButton = new javax.swing.JButton();
        AMaintenanceButton = new javax.swing.JButton();
        AStatusLabelValue = new javax.swing.JLabel();
        Labeler = new javax.swing.JPanel();
        LStatusLabel = new javax.swing.JLabel();
        PBLabelStatusValue5 = new javax.swing.JLabel();
        LPRLabel = new javax.swing.JLabel();
        LPRValue = new javax.swing.JSpinner();
        LDetailsButton = new javax.swing.JButton();
        LBreakButton = new javax.swing.JButton();
        LMaintenanceButton = new javax.swing.JButton();
        QCStatusLabelValue = new javax.swing.JLabel();
        Palletizer = new javax.swing.JPanel();
        PStatusLabel = new javax.swing.JLabel();
        PBLabelStatusValue6 = new javax.swing.JLabel();
        PPRLabel = new javax.swing.JLabel();
        PPRValue = new javax.swing.JSpinner();
        PDetailsButton = new javax.swing.JButton();
        PBreakButton = new javax.swing.JButton();
        PMaintenanceButton = new javax.swing.JButton();
        QCStatusLabelValue3 = new javax.swing.JLabel();
        Boxer = new javax.swing.JPanel();
        BStatusLabel = new javax.swing.JLabel();
        PBLabelStatusValue7 = new javax.swing.JLabel();
        BPRLabel = new javax.swing.JLabel();
        BPRValue = new javax.swing.JSpinner();
        BDetailsButton = new javax.swing.JButton();
        BBreakButton = new javax.swing.JButton();
        BMaintenanceButton = new javax.swing.JButton();
        QCStatusLabelValue2 = new javax.swing.JLabel();
        ProducerB = new javax.swing.JPanel();
        PBStatusLabel1 = new javax.swing.JLabel();
        PBLabelStatusValue8 = new javax.swing.JLabel();
        PBPRLabel = new javax.swing.JLabel();
        PBPRValue = new javax.swing.JSpinner();
        PBDetailsButton = new javax.swing.JButton();
        PBBreakButton = new javax.swing.JButton();
        PBMaintenanceButton = new javax.swing.JButton();
        PBStatusLabelValue = new javax.swing.JLabel();

        ProducerBPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assembler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        PBStatusLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PBStatusLabel3.setText("Status: ");

        PBPRLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PBPRLabel3.setText("Production Rate: ");

        PBDetailsButton3.setLabel("Details...");
        PBDetailsButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBDetailsButton3ActionPerformed(evt);
            }
        });

        PBBreakButton3.setLabel("Break");

        PBMaintenanceButton3.setLabel("Maintenance");

        javax.swing.GroupLayout ProducerBPanel3Layout = new javax.swing.GroupLayout(ProducerBPanel3);
        ProducerBPanel3.setLayout(ProducerBPanel3Layout);
        ProducerBPanel3Layout.setHorizontalGroup(
            ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(PBDetailsButton3)
                        .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PBStatusLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                                .addComponent(PBPRLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PBPRValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                        .addComponent(PBBreakButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PBMaintenanceButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProducerBPanel3Layout.setVerticalGroup(
            ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PBLabelStatusValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(ProducerBPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PBStatusLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PBPRLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PBPRValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(PBDetailsButton3)
                .addGap(18, 18, 18)
                .addGroup(ProducerBPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PBBreakButton3)
                    .addComponent(PBMaintenanceButton3))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VirtualProductLine");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 650));

        ProducerC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producer C", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        PCStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PCStatusLabel.setText("Status: ");

        PCPRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PCPRLabel.setText("Production Rate: ");

        PCDetailsButton.setLabel("Details...");
        PCDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCDetailsButtonActionPerformed(evt);
            }
        });

        PCBreakButton.setLabel("Break");

        PCMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout ProducerCLayout = new javax.swing.GroupLayout(ProducerC);
        ProducerC.setLayout(ProducerCLayout);
        ProducerCLayout.setHorizontalGroup(
            ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PCDetailsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PCStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ProducerCLayout.createSequentialGroup()
                        .addComponent(PCPRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PCPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProducerCLayout.createSequentialGroup()
                        .addComponent(PCBreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PCMaintenanceButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProducerCLayout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(PCStatusLabelValue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(110, 110, 110)))
        );
        ProducerCLayout.setVerticalGroup(
            ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerCLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(PBLabelStatusValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(ProducerCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PCStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PCPRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PCPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(PCDetailsButton)
                .addGap(18, 18, 18)
                .addGroup(ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PCBreakButton)
                    .addComponent(PCMaintenanceButton))
                .addContainerGap())
            .addGroup(ProducerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ProducerCLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(PCStatusLabelValue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(107, 107, 107)))
        );

        QualityChecker.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quality Checker", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        QCStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        QCStatusLabel.setText("Status: ");

        QCPRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        QCPRLabel.setText("Production Rate: ");

        QCDetailsButton.setLabel("Details...");
        QCDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QCDetailsButtonActionPerformed(evt);
            }
        });

        QCBreakButton.setLabel("Break");

        QCMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout QualityCheckerLayout = new javax.swing.GroupLayout(QualityChecker);
        QualityChecker.setLayout(QualityCheckerLayout);
        QualityCheckerLayout.setHorizontalGroup(
            QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QualityCheckerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QCDetailsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(QCStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(QualityCheckerLayout.createSequentialGroup()
                        .addComponent(QCPRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QCPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(QualityCheckerLayout.createSequentialGroup()
                        .addComponent(QCBreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QCMaintenanceButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(QualityCheckerLayout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(QCStatusLabelValue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(110, 110, 110)))
        );
        QualityCheckerLayout.setVerticalGroup(
            QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QualityCheckerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PBLabelStatusValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(QualityCheckerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QCStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QCPRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QCPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(QCDetailsButton)
                .addGap(18, 18, 18)
                .addGroup(QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QCBreakButton)
                    .addComponent(QCMaintenanceButton))
                .addContainerGap())
            .addGroup(QualityCheckerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(QualityCheckerLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(QCStatusLabelValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(107, Short.MAX_VALUE)))
        );

        Assembler.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assembler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        AStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AStatusLabel.setText("Status: ");

        APRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        APRLabel.setText("Production Rate: ");

        ADetailsButton.setLabel("Details...");
        ADetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADetailsButtonActionPerformed(evt);
            }
        });

        ABreakButton.setLabel("Break");

        AMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout AssemblerLayout = new javax.swing.GroupLayout(Assembler);
        Assembler.setLayout(AssemblerLayout);
        AssemblerLayout.setHorizontalGroup(
            AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssemblerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADetailsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AssemblerLayout.createSequentialGroup()
                        .addComponent(AStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AStatusLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AssemblerLayout.createSequentialGroup()
                        .addComponent(APRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(APRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AssemblerLayout.createSequentialGroup()
                        .addComponent(ABreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AMaintenanceButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AssemblerLayout.setVerticalGroup(
            AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssemblerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PBLabelStatusValue4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(AssemblerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AStatusLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(APRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(APRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(ADetailsButton)
                .addGap(18, 18, 18)
                .addGroup(AssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ABreakButton)
                    .addComponent(AMaintenanceButton))
                .addContainerGap())
        );

        Labeler.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Labeler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        LStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LStatusLabel.setText("Status: ");

        LPRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LPRLabel.setText("Production Rate: ");

        LDetailsButton.setLabel("Details...");
        LDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDetailsButtonActionPerformed(evt);
            }
        });

        LBreakButton.setLabel("Break");

        LMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout LabelerLayout = new javax.swing.GroupLayout(Labeler);
        Labeler.setLayout(LabelerLayout);
        LabelerLayout.setHorizontalGroup(
            LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDetailsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LabelerLayout.createSequentialGroup()
                        .addComponent(LStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(QCStatusLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(LabelerLayout.createSequentialGroup()
                        .addComponent(LPRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LabelerLayout.createSequentialGroup()
                        .addComponent(LBreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LMaintenanceButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LabelerLayout.setVerticalGroup(
            LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QCStatusLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LabelerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PBLabelStatusValue5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(LabelerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LPRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(LDetailsButton)
                        .addGap(18, 18, 18)
                        .addGroup(LabelerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBreakButton)
                            .addComponent(LMaintenanceButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        Palletizer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Palletizer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        PStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PStatusLabel.setText("Status: ");

        PPRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PPRLabel.setText("Production Rate: ");

        PDetailsButton.setLabel("Details...");
        PDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDetailsButtonActionPerformed(evt);
            }
        });

        PBreakButton.setLabel("Break");

        PMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout PalletizerLayout = new javax.swing.GroupLayout(Palletizer);
        Palletizer.setLayout(PalletizerLayout);
        PalletizerLayout.setHorizontalGroup(
            PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PalletizerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PDetailsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PalletizerLayout.createSequentialGroup()
                        .addComponent(PStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(QCStatusLabelValue3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PalletizerLayout.createSequentialGroup()
                        .addComponent(PPRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PalletizerLayout.createSequentialGroup()
                        .addComponent(PBreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PMaintenanceButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PalletizerLayout.setVerticalGroup(
            PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PalletizerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(QCStatusLabelValue3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PalletizerLayout.createSequentialGroup()
                        .addGroup(PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PPRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(PDetailsButton)
                        .addGap(18, 18, 18)
                        .addGroup(PalletizerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PBreakButton)
                            .addComponent(PMaintenanceButton)))
                    .addComponent(PBLabelStatusValue6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        Boxer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Boxer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        BStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BStatusLabel.setText("Status: ");

        BPRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BPRLabel.setText("Production Rate: ");

        BDetailsButton.setLabel("Details...");
        BDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDetailsButtonActionPerformed(evt);
            }
        });

        BBreakButton.setLabel("Break");

        BMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout BoxerLayout = new javax.swing.GroupLayout(Boxer);
        Boxer.setLayout(BoxerLayout);
        BoxerLayout.setHorizontalGroup(
            BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BDetailsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BoxerLayout.createSequentialGroup()
                        .addComponent(BStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(QCStatusLabelValue2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BoxerLayout.createSequentialGroup()
                        .addComponent(BPRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BoxerLayout.createSequentialGroup()
                        .addComponent(BBreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BMaintenanceButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BoxerLayout.setVerticalGroup(
            BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(QCStatusLabelValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoxerLayout.createSequentialGroup()
                        .addGroup(BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BPRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(BDetailsButton)
                        .addGap(18, 18, 18)
                        .addGroup(BoxerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BBreakButton)
                            .addComponent(BMaintenanceButton)))
                    .addComponent(PBLabelStatusValue7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        ProducerB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producer B", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 0, 14))); // NOI18N

        PBStatusLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PBStatusLabel1.setText("Status: ");

        PBPRLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PBPRLabel.setText("Production Rate: ");

        PBDetailsButton.setLabel("Details...");
        PBDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBDetailsButtonActionPerformed(evt);
            }
        });

        PBBreakButton.setLabel("Break");

        PBMaintenanceButton.setLabel("Maintenance");

        javax.swing.GroupLayout ProducerBLayout = new javax.swing.GroupLayout(ProducerB);
        ProducerB.setLayout(ProducerBLayout);
        ProducerBLayout.setHorizontalGroup(
            ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PBDetailsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProducerBLayout.createSequentialGroup()
                        .addComponent(PBStatusLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(PBStatusLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProducerBLayout.createSequentialGroup()
                        .addComponent(PBPRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PBPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProducerBLayout.createSequentialGroup()
                        .addComponent(PBBreakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PBMaintenanceButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PBLabelStatusValue8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProducerBLayout.setVerticalGroup(
            ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProducerBLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PBLabelStatusValue8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(ProducerBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PBStatusLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PBStatusLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PBPRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PBPRValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(PBDetailsButton)
                .addGap(18, 18, 18)
                .addGroup(ProducerBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PBBreakButton)
                    .addComponent(PBMaintenanceButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Labeler, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProducerB, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProducerC, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boxer, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Palletizer, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Assembler, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QualityChecker, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProducerC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Assembler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QualityChecker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProducerB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Boxer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Palletizer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Labeler, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PCDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCDetailsButtonActionPerformed

    private void QCDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QCDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QCDetailsButtonActionPerformed

    private void PBDetailsButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBDetailsButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PBDetailsButton3ActionPerformed

    private void ADetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADetailsButtonActionPerformed

    private void LDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LDetailsButtonActionPerformed

    private void PDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDetailsButtonActionPerformed

    private void BDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BDetailsButtonActionPerformed

    private void PBDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PBDetailsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirtualProductLineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VirtualProductLineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirtualProductLineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirtualProductLineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VirtualProductLineGUI(new ConfigurationAgent("configuration.xml")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABreakButton;
    private javax.swing.JButton ADetailsButton;
    private javax.swing.JButton AMaintenanceButton;
    private javax.swing.JLabel APRLabel;
    private javax.swing.JSpinner APRValue;
    private javax.swing.JLabel AStatusLabel;
    private javax.swing.JLabel AStatusLabelValue;
    private javax.swing.JPanel Assembler;
    private javax.swing.JButton BBreakButton;
    private javax.swing.JButton BDetailsButton;
    private javax.swing.JButton BMaintenanceButton;
    private javax.swing.JLabel BPRLabel;
    private javax.swing.JSpinner BPRValue;
    private javax.swing.JLabel BStatusLabel;
    private javax.swing.JPanel Boxer;
    private javax.swing.JButton LBreakButton;
    private javax.swing.JButton LDetailsButton;
    private javax.swing.JButton LMaintenanceButton;
    private javax.swing.JLabel LPRLabel;
    private javax.swing.JSpinner LPRValue;
    private javax.swing.JLabel LStatusLabel;
    private javax.swing.JPanel Labeler;
    private javax.swing.JButton PBBreakButton;
    private javax.swing.JButton PBBreakButton3;
    private javax.swing.JButton PBDetailsButton;
    private javax.swing.JButton PBDetailsButton3;
    private javax.swing.JLabel PBLabelStatusValue1;
    private javax.swing.JLabel PBLabelStatusValue2;
    private javax.swing.JLabel PBLabelStatusValue3;
    private javax.swing.JLabel PBLabelStatusValue4;
    private javax.swing.JLabel PBLabelStatusValue5;
    private javax.swing.JLabel PBLabelStatusValue6;
    private javax.swing.JLabel PBLabelStatusValue7;
    private javax.swing.JLabel PBLabelStatusValue8;
    private javax.swing.JButton PBMaintenanceButton;
    private javax.swing.JButton PBMaintenanceButton3;
    private javax.swing.JLabel PBPRLabel;
    private javax.swing.JLabel PBPRLabel3;
    private javax.swing.JSpinner PBPRValue;
    private javax.swing.JSpinner PBPRValue3;
    private javax.swing.JLabel PBStatusLabel1;
    private javax.swing.JLabel PBStatusLabel3;
    private javax.swing.JLabel PBStatusLabelValue;
    private javax.swing.JButton PBreakButton;
    private javax.swing.JButton PCBreakButton;
    private javax.swing.JButton PCDetailsButton;
    private javax.swing.JButton PCMaintenanceButton;
    private javax.swing.JLabel PCPRLabel;
    private javax.swing.JSpinner PCPRValue;
    private javax.swing.JLabel PCStatusLabel;
    private javax.swing.JLabel PCStatusLabelValue1;
    private javax.swing.JButton PDetailsButton;
    private javax.swing.JButton PMaintenanceButton;
    private javax.swing.JLabel PPRLabel;
    private javax.swing.JSpinner PPRValue;
    private javax.swing.JLabel PStatusLabel;
    private javax.swing.JPanel Palletizer;
    private javax.swing.JPanel ProducerB;
    private javax.swing.JPanel ProducerBPanel3;
    private javax.swing.JPanel ProducerC;
    private javax.swing.JButton QCBreakButton;
    private javax.swing.JButton QCDetailsButton;
    private javax.swing.JButton QCMaintenanceButton;
    private javax.swing.JLabel QCPRLabel;
    private javax.swing.JSpinner QCPRValue;
    private javax.swing.JLabel QCStatusLabel;
    private javax.swing.JLabel QCStatusLabelValue;
    private javax.swing.JLabel QCStatusLabelValue1;
    private javax.swing.JLabel QCStatusLabelValue2;
    private javax.swing.JLabel QCStatusLabelValue3;
    private javax.swing.JPanel QualityChecker;
    // End of variables declaration//GEN-END:variables
}
